from constants import (
    STATUS_CANCELLED,
    STATUS_COMPLETED,
    STATUS_CONFIRMED,
    STATUS_CREATED,
    STATUS_DELIVERED,
    STATUS_IN_TRANSIT,
    STATUS_READY_FOR_PICKUP,
)


STATUS_FLOW = {
    STATUS_CREATED: [
        STATUS_CONFIRMED,
        STATUS_CANCELLED,
    ],
    STATUS_CONFIRMED: [
        STATUS_IN_TRANSIT,
        STATUS_CANCELLED,
        STATUS_READY_FOR_PICKUP,
    ],
    STATUS_IN_TRANSIT: [
        STATUS_DELIVERED,
        STATUS_CANCELLED,
    ],
    STATUS_DELIVERED: [],
    STATUS_CANCELLED: [],
    STATUS_READY_FOR_PICKUP: [
        STATUS_COMPLETED,
        STATUS_CANCELLED,
    ],
    STATUS_COMPLETED: [],
}
